---
"/insights/platform/catalog":
  :display_name: Catalog
  :dependent_applications:
  - "/insights/platform/topological-inventory"
  :supported_source_types:
  - ansible-tower
  :supported_authentication_types:
    ansible-tower:
    - username_password
"/insights/platform/cost-management":
  :display_name: Cost Management
  :dependent_applications: []
  :supported_source_types:
  - amazon
  - azure
  - openshift
  :supported_authentication_types:
    amazon:
    - arn
    azure:
    - tenant_id_client_id_client_secret
    openshift:
    - token
"/insights/platform/cloud-meter":
  :display_name: Cloud Meter
  :dependent_applications: []
  :supported_source_types:
  - amazon
  :supported_authentication_types:
    amazon:
    - cloud-meter-arn
"/insights/platform/topological-inventory":
  :display_name: Topological Inventory
  :dependent_applications: []
  :supported_source_types:
  - amazon
  - ansible-tower
  - azure
  - openshift
  :supported_authentication_types:
    amazon:
    - access_key_secret_key
    ansible-tower:
    - username_password
    azure:
    - tenant_id_client_id_client_secret
    openshift:
    - token
"/insights/platform/fifi":
  :display_name: Find It Fix It
  :dependent_applications: []
  :supported_source_types:
  - satellite
  :supported_authentication_types:
    satellite:
    - receptor_node
